"""Skill-Aware Traders (Together AI) - Agents using learned skills with open-source models.

Together AI versions of SkillAwareTrader and SkillOnlyTrader, using gpt-oss or
other open-source models. Ideal for cost-effective deployment or local inference.
"""

from __future__ import annotations

import os
from typing import Any, Optional

from langchain_openai import ChatOpenAI

from agent_arena.agentic.base import AgenticTrader
from agent_arena.agentic.graph import create_trading_graph
from agent_arena.agentic.tools.skills import SkillRecommendationTool, TradingSkillsTool
from agent_arena.core.agent import BaseAgent
from agent_arena.core.models import Decision


# Model shortcuts for Together AI
TOGETHER_MODELS = {
    "gpt-oss-20b": "openai/gpt-oss-20b",
    "gpt-oss-120b": "openai/gpt-oss-120b",
    "llama-4-scout": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
    "llama-4-maverick": "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
    "qwen-2.5-72b": "Qwen/Qwen2.5-72B-Instruct-Turbo",
    "deepseek-v3.1": "deepseek-ai/DeepSeek-V3.1",
}


class SkillAwareTogetherTrader(AgenticTrader):
    """
    Skill-aware trading agent using Together AI open-source models.

    This agent extends AgenticTrader with:
    1. Access to skills generated by Observer Agent
    2. Skill-aware system prompt
    3. Tools for querying and applying skills

    Uses gpt-oss or similar open-source models instead of Claude,
    reducing costs by ~97% while maintaining tool-calling capability.

    Example config:
        config:
            model: gpt-oss-20b          # or gpt-oss-120b for better quality
            base_url: https://api.together.xyz/v1  # or local endpoint
            max_iterations: 4
            skills_dir: "skills"
            always_check_skills: true
    """

    def __init__(self, agent_id: str, name: str, config: Optional[dict] = None):
        super().__init__(agent_id, name, config)
        config = config or {}

        # Model configuration - default to gpt-oss-20b (best value)
        model_input = config.get("model", "gpt-oss-20b")
        self.model = TOGETHER_MODELS.get(model_input, model_input)

        # API configuration
        self.base_url = config.get("base_url", "https://api.together.xyz/v1")
        self.api_key_env = config.get("api_key_env", "TOGETHER_API_KEY")

        self.max_iterations = config.get("max_iterations", 4)

        # Skills configuration
        self.skills_dir = config.get("skills_dir", "skills")
        self.always_check_skills = config.get("always_check_skills", True)

        # Initialize skills tools
        self._skills_tool = TradingSkillsTool(skills_dir=self.skills_dir)
        self._skill_recommend_tool = SkillRecommendationTool(skills_tool=self._skills_tool)

        # Add skills tools to the tool list (inherited tools + skills)
        self.tools.extend([
            self._skills_tool,
            self._skill_recommend_tool,
        ])

    async def on_start(self) -> None:
        """Initialize Together AI LLM and graph with skill-aware system prompt."""
        api_key = os.environ.get(self.api_key_env, "")

        # Use LangChain's OpenAI wrapper with Together's API
        self._llm = ChatOpenAI(
            model=self.model,
            temperature=self.temperature,
            max_tokens=2048,
            api_key=api_key,
            base_url=self.base_url,
        ).bind_tools(self.tools)

        # Create the trading graph with skill-aware prompt
        self._graph = create_trading_graph(
            llm=self._llm,
            tools=self.tools,
            memory_store=self._memory_store,
            system_prompt=self._build_skill_aware_prompt(),
        )

    def _build_skill_aware_prompt(self) -> str:
        """Build system prompt that emphasizes skill usage."""
        available_skills = self._skills_tool._get_available_skills()
        skills_list = ", ".join(available_skills) if available_skills else "none yet"

        return f"""You are a sophisticated trading agent with access to LEARNED SKILLS.

Unlike basic traders, you can access institutional knowledge accumulated from
analyzing past competition data. This knowledge is stored in skills that you
should consult before making decisions.

AVAILABLE SKILLS: {skills_list}

HOW TO USE SKILLS:
1. Use `trading_skills` tool to read skill content
2. Use `recommend_skill` tool if unsure which skill is relevant
3. Apply the guidance from skills to your decision-making
4. Document which skills influenced your decision

DECISION WORKFLOW:
1. **Assess situation**: Analyze market data, portfolio state
2. **Consult skills**: {"ALWAYS check" if self.always_check_skills else "Check when relevant"}
   - For market analysis → check `market-regimes`
   - For position sizing → check `risk-management`
   - For general guidance → check `trading-wisdom`
3. **Apply tools**: Use technical analysis, risk calculator, etc.
4. **Make decision**: Combine skill guidance with current analysis

SKILL PRIORITY:
- Skills represent STATISTICAL EVIDENCE from real competition data
- Higher confidence skills should carry more weight
- If skill guidance conflicts with your analysis, note this in reasoning
- When in doubt, follow high-confidence skill rules

CHARACTER:
{self.character or "A disciplined trader who respects historical evidence."}

Remember: Those who don't learn from history are doomed to repeat it.
Use your skills to avoid past mistakes and replicate past successes."""

    async def decide(self, context: dict) -> Decision:
        """Make a skill-informed trading decision."""
        # Ensure graph is created
        if self._graph is None:
            await self.on_start()

        # Get decision from parent class
        decision = await super().decide(context)

        # Add skill-aware metadata
        decision.metadata["skill_aware"] = True
        decision.metadata["provider"] = "together"
        decision.metadata["skills_available"] = self._skills_tool._get_available_skills()

        # Check if skills were used (look in tool results)
        tool_calls = decision.metadata.get("thoughts", [])
        skills_consulted = []
        for thought in tool_calls:
            if isinstance(thought, str):
                if "trading_skills" in thought.lower():
                    skills_consulted.append("trading_skills")
                if "recommend_skill" in thought.lower():
                    skills_consulted.append("recommend_skill")
        decision.metadata["skills_consulted"] = skills_consulted

        return decision


class SkillOnlyTogetherTrader(BaseAgent):
    """
    Minimal skill-based trader using Together AI open-source models.

    This agent ONLY uses skills, no other tools. Demonstrates pure
    skill-based trading without technical analysis tools.

    Uses gpt-oss-20b by default - the cheapest option that still
    handles tool calling well.

    Example config:
        config:
            model: gpt-oss-20b
            base_url: https://api.together.xyz/v1  # or local endpoint
            max_iterations: 2
            skills_dir: "skills"
    """

    def __init__(self, agent_id: str, name: str, config: Optional[dict] = None):
        super().__init__(agent_id, name, config)
        config = config or {}

        # Model configuration - default to gpt-oss-20b (cheapest with good tools)
        model_input = config.get("model", "gpt-oss-20b")
        self.model = TOGETHER_MODELS.get(model_input, model_input)

        # API configuration
        self.base_url = config.get("base_url", "https://api.together.xyz/v1")
        self.api_key_env = config.get("api_key_env", "TOGETHER_API_KEY")

        self.max_iterations = config.get("max_iterations", 2)
        self.temperature = config.get("temperature", 0.5)
        self.character = config.get("character", "")
        self.skills_dir = config.get("skills_dir", "skills")
        self.always_check_skills = True

        # ONLY skills tools, nothing else
        self._skills_tool = TradingSkillsTool(skills_dir=self.skills_dir)
        self._skill_recommend_tool = SkillRecommendationTool(skills_tool=self._skills_tool)
        self.tools = [self._skills_tool, self._skill_recommend_tool]

        # Graph components
        self._graph = None
        self._memory_store = None
        self._storage = None
        self._llm = None

    def set_storage(self, storage: Any) -> None:
        """Set storage (minimal, just for compatibility)."""
        self._storage = storage

    async def on_start(self) -> None:
        """Initialize Together AI LLM and graph."""
        api_key = os.environ.get(self.api_key_env, "")

        # Use LangChain's OpenAI wrapper with Together's API
        self._llm = ChatOpenAI(
            model=self.model,
            temperature=self.temperature,
            max_tokens=1024,
            api_key=api_key,
            base_url=self.base_url,
        ).bind_tools(self.tools)

        # Create the trading graph
        self._graph = create_trading_graph(
            llm=self._llm,
            tools=self.tools,
            memory_store=self._memory_store,
            system_prompt=self._build_skill_only_prompt(),
        )

    def _build_skill_only_prompt(self) -> str:
        """Build prompt emphasizing skill-only approach."""
        available_skills = self._skills_tool._get_available_skills()
        skills_list = ", ".join(available_skills) if available_skills else "none yet"

        return f"""You are a trading agent that makes decisions PURELY based on learned skills.

You do NOT have access to technical analysis tools or complex indicators.
Your only source of trading knowledge is the skills that have been learned
from past competition data.

AVAILABLE SKILLS: {skills_list}

YOUR TOOLS:
- `trading_skills`: Read skill content for guidance
- `recommend_skill`: Get recommendation on which skill to check

DECISION PROCESS:
1. Check `trading_wisdom` for general guidance
2. Identify market regime (from context) and check `market-regimes`
3. Use `risk-management` for position sizing guidance
4. Make decision based on skill recommendations

IMPORTANT:
- You CANNOT calculate RSI, SMA, or other technical indicators
- You MUST rely on skill guidance
- If no relevant skill exists, be conservative (hold or small position)
- Always cite which skill informed your decision

CHARACTER:
{self.character or "A disciplined follower of learned wisdom."}

Trust the skills - they represent real statistical evidence from competition data."""

    async def decide(self, context: dict) -> Decision:
        """Make a skill-only trading decision."""
        from decimal import Decimal

        # Ensure graph is created
        if self._graph is None:
            await self.on_start()

        # Add agent_id to context for tools
        context["agent_id"] = self.agent_id

        # Build initial state
        from agent_arena.agentic.state import AgentState
        initial_state: AgentState = {
            "context": context,
            "agent_id": self.agent_id,
            "messages": [],
            "tool_calls": [],
            "tool_results": [],
            "thoughts": [],
            "iteration": 0,
            "max_iterations": self.max_iterations,
            "should_continue": True,
            "decision": None,
            "memories_retrieved": [],
        }

        try:
            from datetime import datetime
            start_time = datetime.utcnow()
            result = await self._graph.ainvoke(initial_state)
            latency = (datetime.utcnow() - start_time).total_seconds() * 1000

            # Extract decision
            decision_dict = result.get("decision", {})
            if not decision_dict:
                decision_dict = {"action": "hold", "reasoning": "No decision produced"}

            decision = Decision(
                action=decision_dict.get("action", "hold"),
                symbol=decision_dict.get("symbol"),
                size=Decimal(str(decision_dict["size"])) if decision_dict.get("size") else None,
                leverage=decision_dict.get("leverage", 1),
                confidence=decision_dict.get("confidence", 0.5),
                reasoning=decision_dict.get("reasoning", ""),
                metadata={
                    "model": self.model,
                    "provider": "together",
                    "agent_type": "skill_only",
                    "iterations": result.get("iteration", 0),
                    "tool_calls_count": len(result.get("tool_results", [])),
                    "thoughts": result.get("thoughts", []),
                    "latency_ms": latency,
                    "skills_available": self._skills_tool._get_available_skills(),
                },
            )

            return decision

        except Exception as e:
            return Decision(
                action="hold",
                reasoning=f"Skill-only agent error: {str(e)}",
                confidence=0.0,
                metadata={
                    "error": str(e),
                    "agent_type": "skill_only",
                    "provider": "together",
                    "model": self.model,
                },
            )

    async def on_stop(self) -> None:
        """Cleanup on competition end."""
        pass
